-- Generated by AMP for DCS Dedicated Server.
-- Copy this file to the active DCS config location if needed.

cfg =
{
    ["port"] = {{GamePort}},
    ["name"] = "{{ServerName}}",
    ["description"] = "{{ServerDescription}}",
    ["password"] = "{{ServerPassword}}",
    ["maxPlayers"] = {{MaxPlayers}},
    ["listStartIndex"] = 1,
    ["missionList"] =
    {
{{MissionListLuaEntries}}
    },
    ["advanced"] =
    {
        ["resume_mode"] = {{ResumeMode}},
    },
{{ServerSettingsExtra}}
}
